src/blog/urls.py
from django.urls import path

from blog.views import(
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	delete_blog,
	add_reply,
)

#this is for easier reference of the app urls
app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
	path('<slug>/delete', delete_blog, name="delete"),
	path('<slug>/reply', add_reply, name="reply"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#import the view from personal folder, with the function name
from personal.views import (
    home_screen_view,
)

from account.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('scores/', scores_view, name="scores"),
    path('set_grade/', set_grade, name="set_grade"),
    path('view_attempts/', view_attempts, name="view_attempts"),
    path('search/', search_results, name='search_results'),
    path('search2/', search_results2, name='search_results2'),
    path('search3/', search_results3, name='search_results3'),
    path('delete/', del_user, name="delete"),
    path('quiz/', include('quiz.urls')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




src/blog/models.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver

def upload_location(instance, filename, **kwargs ):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
		author_id=str(instance.author.id), title=str(instance.title), filename=filename)
	return file_path

class BlogPost(models.Model):
	title = models.CharField(max_length=50,null=False,blank=False)
	body = models.TextField(max_length=50,null=False,blank=False)
	image = models.ImageField(upload_to=upload_location,null=False,blank=False)
	file = models.FileField(upload_to=upload_location,default='static/gov.png')
	date_published = models.DateTimeField(auto_now_add=True,verbose_name="date published")
	date_updated = models.DateTimeField(auto_now=True,verbose_name="date updated")
	author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	slug = models.SlugField(blank=True,unique=True)

	def __str__(self):
		return '%s' % (self.title)

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete(False)

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug=slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

class Reply(models.Model):
	post = models.ForeignKey(BlogPost, related_name="replies", on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	body = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '%s - %s' % (self.post.title, self.name)

src/blog/forms.py
from django import forms
from blog.models import BlogPost, Reply

class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image', 'file',]

class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image', 'file']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']
		if self.cleaned_data['file']:
			blog_post.file = self.cleaned_data['file']

		if commit:
			blog_post.save()
		return blog_post

class ReplyForm(forms.ModelForm):

	class Meta:
		model = Reply
		fields = ['post','name','body']

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import BlogPost, Reply
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm, ReplyForm
from account.models import Account
from django.db.models import Q
from hitcount.views import HitCountMixin
from hitcount.models import HitCount

def create_blog_view (request):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		form = CreateBlogPostForm()
		context['success_message'] = "Posted"

	context['form'] = form

	return render(request, "blog/create_blog.html", context)

def detail_blog_view(request, slug):

	context = {}

	post = get_object_or_404(BlogPost, slug=slug)

	if request.method == 'POST':
		form = ReplyForm(request.POST)

		if form.is_valid():
			obj = form.save(commit=False)
			obj.post = post
			obj.save()

			return redirect('/')

	else:
		form = ReplyForm()

	context['blog_post'] = post
	context['form'] = form

	hit_count = HitCount.objects.get_for_object(post)

	hit_count_response = HitCountMixin.hit_count(request, hit_count)


	return render(request, 'blog/deatil_blog.html', context)


def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance = blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj 

	form = UpdateBlogPostForm(
		initial = {
			"title": blog_post.title,
			"body": blog_post.body,
			"image": blog_post.image,
		}
	)
	context['form'] = form

	return render(request, 'blog/edit_blog.html', context)

def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

def delete_blog(request, slug):

    blog_post = get_object_or_404(BlogPost, slug=slug)  # Get your current cat

         # If method is POST,
    blog_post.delete()                     # delete the cat.
    return redirect('/') 

def add_reply(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)

	form = ReplyForm(
		initial = {
			"post": blog_post,
			"name": blog_post.author.username,
		}
	)
	context['form'] = form

	return render(request, 'blog/add_reply.html', context)

src/blog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

src/blog/templates/blog/snippets/blog_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
		width: 100%;
	}
	.custom-header {
    background-color: #D3D3D3;
    color: #000000;
	box-shadow: 0 10px 10px rgba(3, 4, 4, 0.5);
    /* Other styles if needed */
	}
</style>

{% if blog_post %}
<div class="container">
	<div class="row">
		<!-- Blog Post -->
		<div class="card  m-auto">
			<div class="card-header custom-header">

			</div>
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title">{{blog_post.title}}</h2>
				</a>
				<p class="card-text">{{blog_post.body|safe|truncatechars:250}}</p>
				<p>
				</p>  
			</div>
			<div class="card-footer text-muted px-2">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>

			<h2>Replies</h2>
			{% if not post.replies.all %}
				<a href="{% url 'blog:reply' post.slug %}">Add Reply</a>
				<br/>
			{% else %}

			<a href="{% url 'blog:reply' post.slug %}">Add Reply</a>

			<br/>
			
				{% for reply in post.replies.all %}
					<strong>
						{{ reply.name }} - 
						{{ reply.date_added }}
					</strong>
					<br/>
					{{ reply.body }}
					<br/>
					<hr>
				{% endfor %}
			{% endif %}

		</div>
	</div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}