src/blog/urls.py
from django.urls import path

from blog.views import(
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	delete_blog,
	add_reply,
)

#this is for easier reference of the app urls
app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
	path('<slug>/delete', delete_blog, name="delete"),
	path('<slug>/reply', add_reply, name="reply"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#import the view from personal folder, with the function name
from personal.views import (
    home_screen_view,
)

from account.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('scores/', scores_view, name="scores"),
    path('set_grade/', set_grade, name="set_grade"),
    path('view_attempts/', view_attempts, name="view_attempts"),
    path('search/', search_results, name='search_results'),
    path('search2/', search_results2, name='search_results2'),
    path('search3/', search_results3, name='search_results3'),
    path('delete/', del_user, name="delete"),
    path('quiz/', include('quiz.urls')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




src/personal/models.py
from django.db import models


# PRIORITY = [
# 	("H", "High"),
# 	("M", "Medium"),
# 	("L", "Low"),
# 	]

# # class Question(models.Model):
# # 	title					= models.CharField(max_length=60)
# # 	question				= models.TextField(max_length=400)
# # 	priority				= models.CharField(max_length=1, choices=PRIORITY)

# # 	def __str__(self):
# # 		return self.title

# # 	# this will change the names on the database on the site
# # 	class Meta:
# # 		verbose_name = "The Question"
# # 		verbose_name_plural = "Peoples Questions"

src/personal/views.py
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from blog.views import get_blog_queryset
from blog.models import BlogPost

BLOG_POSTS_PER_PAGE = 5

def home_screen_view(request, *args, **kwargs):
	
	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
	


	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "personal/home.html", context)

src/personal/templates/personal/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
	.img {
	  display: block;
	  max-width: 100%;
	  height: auto;
	}
	.custom-button {
    box-shadow: 0 10px 10px rgba(3, 4, 4, 0.5);
	width: 150px;
	justify-content: center;
  	}
	.button-image {
	width: 150px; /* Adjust the width as needed */
	height: 20px; /* Adjust the height as needed */
	margin-right: 5px; /* Add spacing between image and text */
	/* Other styling properties */
	}
	.custom-header {
    background-color: #D3D3D3;
    color: #000000;
	box-shadow: 0 10px 10px rgba(3, 4, 4, 0.5);
	text-align: center;
    /* Other styles if needed */
	}
	.card1 {
		height: 375px;
	}
</style>

<div class="container background">
	
	<div class="row">

		<div class="left-column col-lg-5 offset-lg-2">

			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'jollyroger.png' %}" width="72" height="72">
					<p class="lead"></p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
					<a href="{% url 'quiz_list' %}" class="btn btn-primary">Take a Quiz</a>
					<a href="{% url 'create_quiz' %}" class="btn btn-primary">Create a Quiz</a>
				</div>
			</div>

			<div class="p-1">
				<div class="card card1  create-post-bar d-flex flex-column">
					<div class="card-header custom-header">
						<h5>Welcome to the learning site</h5>
					</div>
					<div class="card-body">
						<br>
						<br>
						<p class="lead" style="text-align: center;">Here you can learn from different subject</p>
						<p class="lead" style="text-align: center;">You can also take quizzes to challenge yourself</p>
						<p class="lead" style="text-align: center;">The top bar can be used for navigation</p>
						<p class="lead" style="text-align: center;">The nav bar to the right can be used to create post</p>
					</div>
				</div>
			</div>


			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">
			<div class="card  create-post-bar d-flex flex-column">
				<div class="card-header custom-header">
					<h5>Navigation</h5>
				</div>
				<br>
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'planet3.gif' %}" width="72" height="72">
				<p class="lead" style="text-align: center;"></p>
				
				<p class="m-auto"><a class=" btn btn-primary custom-button" href="{% url 'study_page' %}">Study</a></p>
				<hr>
				<p class="m-auto"><a class=" btn btn-primary custom-button" href="{% url 'scores' %}" class="btn btn-primary">Scores</a></p>
				<hr>
				<p class="m-auto"><a class=" btn btn-primary custom-button" href="{% url 'blog:create' %}">Create post</a></p>
				<br>
			</div>
		</div>

	</div>
</div>

{% endblock content %}