src/blog/urls.py
from django.urls import path

from blog.views import(
	create_blog_view,
	detail_blog_view,
	edit_blog_view,
	delete_blog,
	add_reply,
)

#this is for easier reference of the app urls
app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
	path('<slug>/delete', delete_blog, name="delete"),
	path('<slug>/reply', add_reply, name="reply"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#import the view from personal folder, with the function name
from personal.views import (
    home_screen_view,
)

from account.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name="home"),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('scores/', scores_view, name="scores"),
    path('set_grade/', set_grade, name="set_grade"),
    path('view_attempts/', view_attempts, name="view_attempts"),
    path('search/', search_results, name='search_results'),
    path('search2/', search_results2, name='search_results2'),
    path('search3/', search_results3, name='search_results3'),
    path('delete/', del_user, name="delete"),
    path('quiz/', include('quiz.urls')),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




src/blog/models.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from django.dispatch import receiver

def upload_location(instance, filename, **kwargs ):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
		author_id=str(instance.author.id), title=str(instance.title), filename=filename)
	return file_path

class BlogPost(models.Model):
	title = models.CharField(max_length=50,null=False,blank=False)
	body = models.TextField(max_length=50,null=False,blank=False)
	image = models.ImageField(upload_to=upload_location,null=False,blank=False)
	file = models.FileField(upload_to=upload_location,default='static/gov.png')
	date_published = models.DateTimeField(auto_now_add=True,verbose_name="date published")
	date_updated = models.DateTimeField(auto_now=True,verbose_name="date updated")
	author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	slug = models.SlugField(blank=True,unique=True)

	def __str__(self):
		return '%s' % (self.title)

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete(False)

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug=slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

class Reply(models.Model):
	post = models.ForeignKey(BlogPost, related_name="replies", on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	body = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '%s - %s' % (self.post.title, self.name)

src/blog/forms.py
from django import forms
from blog.models import BlogPost, Reply

class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image', 'file',]

class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image', 'file']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']
		if self.cleaned_data['file']:
			blog_post.file = self.cleaned_data['file']

		if commit:
			blog_post.save()
		return blog_post

class ReplyForm(forms.ModelForm):

	class Meta:
		model = Reply
		fields = ['post','name','body']

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog.models import BlogPost, Reply
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm, ReplyForm
from account.models import Account
from django.db.models import Q
from hitcount.views import HitCountMixin
from hitcount.models import HitCount

def create_blog_view (request):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		form = CreateBlogPostForm()
		context['success_message'] = "Posted"

	context['form'] = form

	return render(request, "blog/create_blog.html", context)

def detail_blog_view(request, slug):

	context = {}

	post = get_object_or_404(BlogPost, slug=slug)

	if request.method == 'POST':
		form = ReplyForm(request.POST)

		if form.is_valid():
			obj = form.save(commit=False)
			obj.post = post
			obj.save()

			return redirect('/')

	else:
		form = ReplyForm()

	context['blog_post'] = post
	context['form'] = form

	hit_count = HitCount.objects.get_for_object(post)

	hit_count_response = HitCountMixin.hit_count(request, hit_count)


	return render(request, 'blog/deatil_blog.html', context)


def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance = blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj 

	form = UpdateBlogPostForm(
		initial = {
			"title": blog_post.title,
			"body": blog_post.body,
			"image": blog_post.image,
		}
	)
	context['form'] = form

	return render(request, 'blog/edit_blog.html', context)

def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

def delete_blog(request, slug):

    blog_post = get_object_or_404(BlogPost, slug=slug)  # Get your current cat

         # If method is POST,
    blog_post.delete()                     # delete the cat.
    return redirect('/') 

def add_reply(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)

	form = ReplyForm(
		initial = {
			"post": blog_post,
			"name": blog_post.author.username,
		}
	)
	context['form'] = form

	return render(request, 'blog/add_reply.html', context)

src/blog/templates/blog/add_reply.html
{% extends 'base.html' %}
 
{% load hitcount_tags %}

{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

  	.p-3 {
  		margin-bottom: 20px;
  	}

</style>

<div class="container">
	<div class="row">
			<h1>Add Reply</h1>
			<div class="form-group card m-auto">
				<form class="create-form p-3" method="post" action=".">
				{% csrf_token %}

				{{ form.as_table }}

				<input type="submit" value="Add reply">

				</form>
		</div>
	</div>
</div>
{% endblock content %}

src/blog/templates/blog/create_blog.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

  	.p-3 {
  		margin-bottom: 20px;
  	}

	.white-border {
    color: black; /* Set the main text color */
    text-shadow:
        -1px -1px 0 #fff, /* Top-left white shadow */
         1px -1px 0 #fff, /* Top-right white shadow */
        -1px 1px 0 #fff, /* Bottom-left white shadow */
         1px 1px 0 #fff; /* Bottom-right white shadow */
	}

</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			{% if fail_message %}
				<h3 style="color:red; text-align: center;">{{fail_message}}</h3>
			{% endif %}
			
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label class="white-border" for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label class="white-border" for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group p-2">
					<label class="white-border" for="id_image">Upload Image</label>
					<input type="file" name="image" id="id_image" accept="image/*" required>
				</div>

				<!-- File Upload -->
				<div class="form-group p-2">
					<label class="white-border" for="id_file">Upload File</label>
					<input type="file" name="file" id="id_file" accept="file/*">
				</div>


				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>




{% endblock content %}

src/blog/templates/blog/deatil_blog.html
{% extends 'base.html' %}
 
{% load hitcount_tags %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style type="text/css">
	.card {
		height: 75%;
		width: 75%;
	}

	.container{
		padding: 20px;
	}

	.card-img-top {
  width: 80%; // Required because we use flexbox and this inherently applies align-self: stretch
  @include border-top-radius($card-inner-border-radius);
	}

</style>

<body>
	<div class="container">
		<div class="row">
			<div class="card border-primary m-auto">
				<img class="card-img-bottom" src="{{blog_post.image.url}}">
				<div class="card-body mb-2">
					<h2 class="card-title">{{blog_post.title}}</h2>
					<p class="card-text">{{blog_post.body|safe}}</p>
					<p class="card-text">Attached File: <a href="path_to_file" download="{{blog_post.file.url}}">Download</a></p>
						{% if blog_post.author == request.user or request.user.is_admin %}
							<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Edit</a> 
							<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
							  Delete Post
							</button>
							<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							  <div class="modal-dialog">
							    <div class="modal-content">
							      <div class="modal-header">
							        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
							        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
							      </div>
							      <div class="modal-body">
							        Are you sure you want to delete this post?
							      </div>
							      <div class="modal-footer">
							      	<a href="{% url 'blog:delete' blog_post.slug %}" class="btn btn-danger">Delete</a>
							        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
							      </div>
							    </div>
							  </div>
							</div>
						{% endif %}
						<div>
						</div>
					</p>
				</div>
				<div class="card-footer text-muted">
					Updated on {{blog_post.date_updated}} by {{blog_post.author}} | {% get_hit_count for blog_post %}
					<i class="fa fa-eye"></i>
				</div>

			</div>
		</div>
	</div>

</body>
{% endblock content %}

src/blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" value="{{form.initial.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." 
					required>{{form.initial.body}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group p-3" id="id_image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				<input type="file" name="file" id="id_file_file" accept="file/*" onchange="readURL(this)">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Edit</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

<script type="text/javascript">
	document.getElementById('id_file_group').onclick = function(event){
    	document.getElementById('id_file_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_file_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}